import {
  ArrowClockwise,
  ArrowLeft,
  ArrowRight,
  ArrowSquareOut,
  BookBookmark,
  BookOpen,
  Books,
  CalendarBlank,
  CaretLeft,
  CaretRight,
  Check,
  CheckCircle,
  Circle,
  Clock,
  Download,
  Eye,
  EyeSlash,
  FileText,
  FilmSlate,
  Fire,
  FloppyDisk,
  GithubLogo,
  Globe,
  Heart,
  House,
  ImageBroken,
  Lightning,
  List,
  MagicWand,
  MagnifyingGlass,
  Moon,
  PauseCircle,
  PencilSimple,
  Play,
  PlayCircle,
  Pulse,
  Question,
  Scroll,
  SignIn,
  SignOut,
  SlidersHorizontal,
  Sparkle,
  SpinnerGap,
  Stack,
  Star,
  Sun,
  TrendDown,
  Trash,
  TwitterLogo,
  Upload,
  User,
  UserPlus,
  Users,
  Warning,
  WarningCircle,
  X,
  XCircle,
  XIcon,
  type Icon,
} from "@phosphor-icons/react";

// Keep existing app imports stable while Phosphor becomes the backing library.
export type LucideIcon = Icon;

export {
  Pulse as Activity,
  WarningCircle as AlertCircle,
  Warning as AlertTriangle,
  ArrowLeft,
  ArrowRight,
  BookBookmark as BookMarked,
  BookOpen,
  CalendarBlank as Calendar,
  Check,
  CheckCircle as CheckCircle2,
  CaretLeft as ChevronLeft,
  CaretRight as ChevronRight,
  Circle,
  PauseCircle as CirclePause,
  Clock,
  Clock as Clock3,
  Download,
  PencilSimple as Edit,
  ArrowSquareOut as ExternalLink,
  Eye,
  EyeSlash as EyeOff,
  FileText,
  FilmSlate as Film,
  Fire as Flame,
  GithubLogo as Github,
  Globe,
  Heart,
  Question as HelpCircle,
  House as Home,
  ImageBroken as ImageOff,
  Stack as Layers,
  Books as Library,
  SpinnerGap as Loader,
  SpinnerGap as Loader2,
  SignIn as LogIn,
  SignOut as LogOut,
  List as Menu,
  Moon,
  PauseCircle,
  Play,
  PlayCircle,
  ArrowClockwise as RefreshCw,
  FloppyDisk as Save,
  Scroll as ScrollText,
  MagnifyingGlass as Search,
  SlidersHorizontal,
  Sparkle as Sparkles,
  Star,
  Sun,
  Trash as Trash2,
  TrendDown as TrendingDown,
  TwitterLogo as Twitter,
  Upload,
  User,
  UserPlus,
  Users,
  MagicWand as Wand2,
  X,
  XCircle,
  XIcon,
  Lightning as Zap,
};
